kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test-cluster
networking:
    apiServerAddress: "127.0.0.1"
    apiServerPort: 6443
    podSubnet: "10.244.0.0/16"
    serviceSubnet: "10.96.0.0/16"
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
      - containerPort: 80
        hostPort: 8088
        listenAddress: "127.0.0.1"
      - containerPort: 443
        hostPort: 4343
        listenAddress: "127.0.0.1"
- role: worker
- role: worker
- role: worker
