apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  completions: 5
  parallelism: 2
  template:
    spec:
      containers:
      - name: example
        image: busybox
        command: ["echo", "Hello World"]
      restartPolicy: Never
